export default () => ({
  port: parseInt(process.env.PORT ?? '3001', 10) || 3001,
  jwt: {
    secret:
      process.env.JWT_SECRET ||
      'zentrion-orchestrator-secret-key-change-in-prod',
    expiresIn: process.env.JWT_EXPIRES_IN || '24h',
  },
  telemetry: {
    generationIntervalMs:
      parseInt(process.env.TELEMETRY_INTERVAL ?? '2000', 10) || 2000,
    burstSize: parseInt(process.env.TELEMETRY_BURST ?? '5', 10) || 5,
  },
  anomaly: {
    detectionIntervalMs:
      parseInt(process.env.ANOMALY_INTERVAL ?? '5000', 10) || 5000,
    suspiciousThreshold: 3,
  },
  policy: {
    autoGenerateDrafts: process.env.POLICY_AUTO_GENERATE !== 'false',
  },
});
