/**
 * Shared domain types used across modules.
 *
 * These are *transport* types — shapes returned by the API or emitted on the
 * internal event bus. They are deliberately independent of the TypeORM
 * entities (`src/modules/database/entities/*`) so that persistence fields
 * (DB ids, timestamps, relations) never leak into API responses.
 */

// ---------------------------------------------------------------------------
// Telemetry
// ---------------------------------------------------------------------------

/**
 * A single parsed request captured from an Istio Envoy access log.
 * Produced by the Istio watcher and persisted as a `TelemetryLog` row.
 */
export interface ParsedRequest {
  /** Internal UUID generated by the watcher. */
  id: string;
  /** ISO-8601 timestamp of when the request was observed. */
  timestamp: string;
  /** Source workload name (pod/service). */
  source: string;
  /** Source pod IP. */
  sourceIp: string;
  /** HTTP method (GET, POST, ...). */
  method: string;
  /** Request path (may include query string). */
  path: string;
  /** HTTP response status code. */
  status: number;
  /** End-to-end latency in milliseconds. */
  latencyMs: number;
  /** Logical service the request is attributed to. */
  service: string;
  /** Downstream service the request was sent to, when known. */
  destService?: string;
  userAgent?: string;
  /** Request body size in bytes. */
  requestSize?: number;
  /** Response body size in bytes. */
  responseSize?: number;
}

/**
 * Aggregated per-service statistics surfaced to the dashboard.
 */
export interface ServiceInfo {
  name: string;
  namespace: string;
  requestsPerSecond: number;
  errorRate: number;
  avgLatency: number;
  /** ISO timestamp of last observed traffic. */
  lastSeen: string;
  /** Names of services this service calls. */
  dependencies: string[];
  /** K8s labels copied from the owning deployment. */
  labels: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Anomalies
// ---------------------------------------------------------------------------

/** Discriminator for the different rule-based detectors. */
export type AnomalyType =
  | 'UNUSUAL_SOURCE'
  | 'UNEXPECTED_COMMUNICATION'
  | 'NEW_ENDPOINT'
  | 'HIGH_ERROR_RATE'
  | 'TRAFFIC_SPIKE'
  | 'SUSPICIOUS_PATTERN'
  | 'LATENCY_ANOMALY'
  | 'UNAUTHORIZED_ACCESS';

/** Severity tier used to drive UI colour and policy auto-generation. */
export type AnomalySeverity = 'low' | 'medium' | 'high' | 'critical';

/** Detected anomaly surfaced on the dashboard and archived as an AnomalyRecord CRD. */
export interface Anomaly {
  id: string;
  timestamp: string;
  service: string;
  type: AnomalyType;
  severity: AnomalySeverity;
  /** Human-readable description of what the detector found. */
  details: string;
  /** IDs of telemetry logs that triggered this anomaly. */
  associatedLogs: string[];
  /** Id of a policy draft auto-generated from this anomaly, if any. */
  suggestedPolicyDraftId?: string;
  metadata?: Record<string, any>;
}

// ---------------------------------------------------------------------------
// Policies
// ---------------------------------------------------------------------------

/** Lifecycle states of a generated Istio AuthorizationPolicy draft. */
export type PolicyStatus = 'pending' | 'approved' | 'rejected' | 'applied';

/**
 * A draft `AuthorizationPolicy` manifest queued for human review.
 * Produced automatically by the policy service in response to an anomaly, or
 * created manually by an admin.
 */
export interface PolicyDraft {
  id: string;
  createdAt: string;
  createdBy: string;
  service: string;
  namespace: string;
  /** Full YAML of the `AuthorizationPolicy` manifest. */
  yaml: string;
  status: PolicyStatus;
  /** Justification shown in the approval UI. */
  reason: string;
  appliedAt?: string;
  approvedBy?: string;
  rejectedBy?: string;
  rejectionReason?: string;
  /** Source anomaly if this draft was auto-generated. */
  anomalyId?: string;
}

/**
 * Immutable audit-trail entry describing an action taken on a policy.
 * One row per lifecycle transition; mirrored into a `PolicyHistory` CRD.
 */
export interface PolicyHistory {
  id: string;
  policyId: string;
  action: 'created' | 'approved' | 'rejected' | 'applied' | 'deleted';
  timestamp: string;
  userId: string;
  details: string;
  metadata?: Record<string, any>;
}

/** Structural shape of an Istio AuthorizationPolicy rule used by the builder. */
export interface AuthorizationRule {
  from?: {
    source?: {
      principals?: string[];
      namespaces?: string[];
      ipBlocks?: string[];
    };
  };
  to?: {
    operation?: {
      methods?: string[];
      paths?: string[];
      ports?: string[];
    };
  };
  when?: Array<{
    key: string;
    values: string[];
  }>;
}

// ---------------------------------------------------------------------------
// Policy chat
// ---------------------------------------------------------------------------

/** One turn in the AI assistant chat for a policy draft. */
export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

// ---------------------------------------------------------------------------
// Users / auth
// ---------------------------------------------------------------------------

/** Transport shape of a user (note: `password` is the stored bcrypt hash). */
export interface User {
  id: string;
  username: string;
  password: string; // bcrypt hash
  role: 'ADMIN' | 'ANALYST' | 'VIEWER';
  email: string;
  createdAt: string;
}

/** JWT payload embedded in issued access tokens. */
export interface JwtPayload {
  /** Subject — the user id. */
  sub: string;
  username: string;
  role: string;
}

// ---------------------------------------------------------------------------
// Kubernetes
// ---------------------------------------------------------------------------

/** Bookkeeping record for manifests that Zentrion has applied to the cluster. */
export interface AppliedManifest {
  id: string;
  kind: string;
  apiVersion: string;
  metadata: {
    name: string;
    namespace: string;
  };
  spec: any;
  appliedAt: string;
  appliedBy: string;
  status: 'active' | 'deleted';
}
